services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 3456:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/posgresql/data

  geo-quiz-api:
    container_name: geo-quiz-api
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres: